// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About Us → Gallery*
 */
export interface AboutUsDocumentDataGalleryItem {
  /**
   * Image field in *About Us → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type AboutUsDocumentDataSlicesSlice = never;

/**
 * Content for About Us documents
 */
interface AboutUsDocumentData {
  /**
   * Heading field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *About Us*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *About Us*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Gallery field in *About Us*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<AboutUsDocumentDataGalleryItem>>;

  /**
   * Slice Zone field in *About Us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutUsDocumentDataSlicesSlice> /**
   * Meta Title field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About Us*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About Us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutUsDocumentData>,
    "about_us",
    Lang
  >;

type AccommodationDocumentDataSlicesSlice =
  | HeroSliceSlice
  | SmallHeroSliceSlice
  | AccommodationListSliceSlice;

/**
 * Content for Accommodation documents
 */
interface AccommodationDocumentData {
  /**
   * Slice Zone field in *Accommodation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AccommodationDocumentDataSlicesSlice> /**
   * Meta Title field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: accommodation.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: accommodation.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Accommodation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Accommodation document from Prismic
 *
 * - **API ID**: `accommodation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccommodationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AccommodationDocumentData>,
    "accommodation",
    Lang
  >;

/**
 * Item in *Accommodation Single → Gallery*
 */
export interface AccommodationSingleDocumentDataGalleryItem {
  /**
   * Image field in *Accommodation Single → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Accommodation Single → Pricing*
 */
export interface AccommodationSingleDocumentDataPricingItem {
  /**
   * Date Start field in *Accommodation Single → Pricing*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.pricing[].date_start
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_start: prismic.DateField;

  /**
   * Date End field in *Accommodation Single → Pricing*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.pricing[].date_end
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_end: prismic.DateField;

  /**
   * Price field in *Accommodation Single → Pricing*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.pricing[].price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Changeover Day field in *Accommodation Single → Pricing*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Flexible
   * - **API ID Path**: accommodation_single.pricing[].changeover_day
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  changeover_day: prismic.SelectField<
    "Flexible" | "Saturday" | "Sunday",
    "filled"
  >;

  /**
   * Minimum Stay field in *Accommodation Single → Pricing*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.pricing[].minimum_stay
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  minimum_stay: prismic.NumberField;
}

/**
 * Item in *Accommodation Single → Discounts*
 */
export interface AccommodationSingleDocumentDataDiscountsItem {
  /**
   * Date Start field in *Accommodation Single → Discounts*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.discounts[].date_start
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_start: prismic.DateField;

  /**
   * Date End field in *Accommodation Single → Discounts*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.discounts[].date_end
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_end: prismic.DateField;

  /**
   * Percentage field in *Accommodation Single → Discounts*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Enter just value (example: for 10% discount, enter 10)
   * - **API ID Path**: accommodation_single.discounts[].percentage
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  percentage: prismic.NumberField;
}

/**
 * Item in *Accommodation Single → Distances*
 */
export interface AccommodationSingleDocumentDataDistancesItem {
  /**
   * Place field in *Accommodation Single → Distances*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.distances[].place
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  place: prismic.KeyTextField;

  /**
   * Distance field in *Accommodation Single → Distances*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.distances[].distance
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  distance: prismic.KeyTextField;
}

/**
 * Item in *Accommodation Single → Reviews*
 */
export interface AccommodationSingleDocumentDataReviewsItem {
  /**
   * Guest field in *Accommodation Single → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.reviews[].guest
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  guest: prismic.KeyTextField;

  /**
   * Guest From field in *Accommodation Single → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.reviews[].guest_from
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  guest_from: prismic.KeyTextField;

  /**
   * Review field in *Accommodation Single → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.reviews[].review
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  review: prismic.KeyTextField;

  /**
   * Stars field in *Accommodation Single → Reviews*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 5
   * - **API ID Path**: accommodation_single.reviews[].stars
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  stars: prismic.SelectField<"5" | "4" | "3" | "2" | "1", "filled">;
}

/**
 * Item in *Accommodation Single → Features*
 */
export interface AccommodationSingleDocumentDataFeaturesItem {
  /**
   * Heated Pool field in *Accommodation Single → Features*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.features[].heatedPool
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  heatedPool: prismic.BooleanField;

  /**
   * Jacuzzi field in *Accommodation Single → Features*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.features[].jacuzzi
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  jacuzzi: prismic.BooleanField;

  /**
   * Sauna field in *Accommodation Single → Features*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.features[].sauna
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  sauna: prismic.BooleanField;

  /**
   * Sea View field in *Accommodation Single → Features*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.features[].seaView
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  seaView: prismic.BooleanField;

  /**
   * Beach field in *Accommodation Single → Features*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.features[].beach
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  beach: prismic.BooleanField;

  /**
   * Playground field in *Accommodation Single → Features*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.features[].playground
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  playground: prismic.BooleanField;

  /**
   * Garden field in *Accommodation Single → Features*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.features[].garden
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  garden: prismic.BooleanField;

  /**
   * Pet Friendly field in *Accommodation Single → Features*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.features[].petFriendly
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  petFriendly: prismic.BooleanField;
}

type AccommodationSingleDocumentDataSlicesSlice =
  | VideoSliceSlice
  | SelectedDestinationsSlice;

/**
 * Content for Accommodation Single documents
 */
interface AccommodationSingleDocumentData {
  /**
   * Heading field in *Accommodation Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * iCal field in *Accommodation Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.ical
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ical: prismic.KeyTextField;

  /**
   * Type field in *Accommodation Single*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Villa
   * - **API ID Path**: accommodation_single.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Villa" | "Cottage" | "Apartment", "filled">;

  /**
   * Gallery field in *Accommodation Single*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<
    Simplify<AccommodationSingleDocumentDataGalleryItem>
  >;

  /**
   * Max. Guests field in *Accommodation Single*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.max_guests
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  max_guests: prismic.NumberField;

  /**
   * GuestsPrikaz field in *Accommodation Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.guestsPrikaz
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  guestsPrikaz: prismic.KeyTextField;

  /**
   * m2 field in *Accommodation Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.sqm
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sqm: prismic.KeyTextField;

  /**
   * Bedrooms field in *Accommodation Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.bedrooms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bedrooms: prismic.KeyTextField;

  /**
   * Bathrooms field in *Accommodation Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.bathrooms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bathrooms: prismic.KeyTextField;

  /**
   * Content field in *Accommodation Single*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Pricing field in *Accommodation Single*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.pricing[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  pricing: prismic.GroupField<
    Simplify<AccommodationSingleDocumentDataPricingItem>
  >;

  /**
   * Security Deposit field in *Accommodation Single*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.security_deposit
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  security_deposit: prismic.NumberField;

  /**
   * Google Map Embed field in *Accommodation Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.google_map_embed
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google_map_embed: prismic.KeyTextField;

  /**
   * Is Featured? field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.isFeatured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isFeatured: prismic.BooleanField;

  /**
   * Discounts field in *Accommodation Single*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.discounts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  discounts: prismic.GroupField<
    Simplify<AccommodationSingleDocumentDataDiscountsItem>
  >;

  /**
   * Distances field in *Accommodation Single*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.distances[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  distances: prismic.GroupField<
    Simplify<AccommodationSingleDocumentDataDistancesItem>
  >;

  /**
   * Reviews field in *Accommodation Single*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.reviews[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  reviews: prismic.GroupField<
    Simplify<AccommodationSingleDocumentDataReviewsItem>
  >;

  /**
   * Infinity Pool field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.infinity_pool
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  infinity_pool: prismic.BooleanField;

  /**
   * Heated Pool field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.heated_pool
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  heated_pool: prismic.BooleanField;

  /**
   * Salt Pool field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.salt_pool
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  salt_pool: prismic.BooleanField;

  /**
   * Swimming Pool field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.swimming_pool
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  swimming_pool: prismic.BooleanField;

  /**
   * Indoor Pool field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.indoor_pool
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  indoor_pool: prismic.BooleanField;

  /**
   * Sauna field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.sauna
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  sauna: prismic.BooleanField;

  /**
   * Jacuzzi field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.jacuzzi
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  jacuzzi: prismic.BooleanField;

  /**
   * Outdoor Shower field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.outdoor_shower
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  outdoor_shower: prismic.BooleanField;

  /**
   * Sun Deck Chairs field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.sun_deck_chairs
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  sun_deck_chairs: prismic.BooleanField;

  /**
   * Lounge Chairs field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.lounge_chairs
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  lounge_chairs: prismic.BooleanField;

  /**
   * Parasol field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.parasol
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  parasol: prismic.BooleanField;

  /**
   * BBQ - Wood field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.bbq_wood
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bbq_wood: prismic.BooleanField;

  /**
   * BBQ - Gas field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.bbq_gas
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bbq_gas: prismic.BooleanField;

  /**
   * Outdoor Dining Area field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.outdoor_dining_area
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  outdoor_dining_area: prismic.BooleanField;

  /**
   * Patio field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.patio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  patio: prismic.BooleanField;

  /**
   * Summer Kitchen field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.summer_kitchen
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  summer_kitchen: prismic.BooleanField;

  /**
   * Balcony field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.balcony
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  balcony: prismic.BooleanField;

  /**
   * Garden field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.garden
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  garden: prismic.BooleanField;

  /**
   * Organic Garden field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.organic_garden
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  organic_garden: prismic.BooleanField;

  /**
   * Playground field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.playground
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  playground: prismic.BooleanField;

  /**
   * Trampoline field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.trampoline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  trampoline: prismic.BooleanField;

  /**
   * Bocce court field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.bocce_court
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bocce_court: prismic.BooleanField;

  /**
   * Table Tennis field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.table_tennis
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  table_tennis: prismic.BooleanField;

  /**
   * Pool Table field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.pool_table
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  pool_table: prismic.BooleanField;

  /**
   * Tennis Court field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.tennis_court
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  tennis_court: prismic.BooleanField;

  /**
   * Fitness Equipment field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.fitness_equipment
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  fitness_equipment: prismic.BooleanField;

  /**
   * Bicycles field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.bicycles
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bicycles: prismic.BooleanField;

  /**
   * Game Consoles field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.game_consoles
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  game_consoles: prismic.BooleanField;

  /**
   * Bluetooth Speakers field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.bluetooth_speakers
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bluetooth_speakers: prismic.BooleanField;

  /**
   * Satellite Cable field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.satellite_cable
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  satellite_cable: prismic.BooleanField;

  /**
   * Smart TV field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.smart_tv
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  smart_tv: prismic.BooleanField;

  /**
   * Streaming Service field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.streaming_service
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  streaming_service: prismic.BooleanField;

  /**
   * Free WiFi field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.free_wifi
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  free_wifi: prismic.BooleanField;

  /**
   * Fully air-conditioned field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.fully_airconditioned
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  fully_airconditioned: prismic.BooleanField;

  /**
   * Partly air-conditioned field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.partly_airconditioned
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  partly_airconditioned: prismic.BooleanField;

  /**
   * Heating field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.heating
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  heating: prismic.BooleanField;

  /**
   * Safe field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.safe
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  safe: prismic.BooleanField;

  /**
   * Game Room field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.game_room
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  game_room: prismic.BooleanField;

  /**
   * Fitness Room field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.fitness_room
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  fitness_room: prismic.BooleanField;

  /**
   * Dishes & Utensils field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.dishes_and_utensils
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  dishes_and_utensils: prismic.BooleanField;

  /**
   * Dishwasher field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.dishwasher
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  dishwasher: prismic.BooleanField;

  /**
   * Microwave field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.microwave
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  microwave: prismic.BooleanField;

  /**
   * Stove field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.stove
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  stove: prismic.BooleanField;

  /**
   * Oven field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.oven
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  oven: prismic.BooleanField;

  /**
   * Refrigerator field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.refrigerator
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  refrigerator: prismic.BooleanField;

  /**
   * Freezer field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.freezer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  freezer: prismic.BooleanField;

  /**
   * Coffee Maker field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.coffee_maker
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  coffee_maker: prismic.BooleanField;

  /**
   * Kettle field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.kettle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  kettle: prismic.BooleanField;

  /**
   * Toaster field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.toaster
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  toaster: prismic.BooleanField;

  /**
   * Highchair field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.highchair
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  highchair: prismic.BooleanField;

  /**
   * King-Size Bed field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.kingsize_bed
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  kingsize_bed: prismic.BooleanField;

  /**
   * Queen-Size Bed field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.queensize_bed
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  queensize_bed: prismic.BooleanField;

  /**
   * Single Bed field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.single_bed
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  single_bed: prismic.BooleanField;

  /**
   * Baby Bed field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.baby_bed
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  baby_bed: prismic.BooleanField;

  /**
   * Workplace field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.workplace
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  workplace: prismic.BooleanField;

  /**
   * Linens Provided field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.linens_provided
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  linens_provided: prismic.BooleanField;

  /**
   * Towels Provided field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.towels_provided
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  towels_provided: prismic.BooleanField;

  /**
   * Pool Towels Provided field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.pool_towels_provided
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  pool_towels_provided: prismic.BooleanField;

  /**
   * Shower field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.shower
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  shower: prismic.BooleanField;

  /**
   * Bathtub field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.bathtub
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bathtub: prismic.BooleanField;

  /**
   * Washing Machine field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.washing_machine
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  washing_machine: prismic.BooleanField;

  /**
   * Dryer field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.dryer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  dryer: prismic.BooleanField;

  /**
   * Iron and Board field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.iron_and_board
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  iron_and_board: prismic.BooleanField;

  /**
   * Private Buoy for the Boat field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.private_buoy_for_the_boat
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  private_buoy_for_the_boat: prismic.BooleanField;

  /**
   * Private Sub Boards field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.private_sub_boards
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  private_sub_boards: prismic.BooleanField;

  /**
   * Beach Access field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.beach_access
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  beach_access: prismic.BooleanField;

  /**
   * Pets Fee field in *Accommodation Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: accommodation_single.pets_fee
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  pets_fee: prismic.BooleanField;

  /**
   * Features field in *Accommodation Single*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.features[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<AccommodationSingleDocumentDataFeaturesItem>
  >;

  /**
   * Location field in *Accommodation Single*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Split Area
   * - **API ID Path**: accommodation_single.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  location: prismic.SelectField<
    | "Split Area"
    | "Omis Area"
    | "Makarska Area"
    | "Dubrovnik Area"
    | "Šibenik Area",
    "filled"
  >;

  /**
   * MyRentID field in *Accommodation Single*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.myRentID
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  myRentID: prismic.NumberField;

  /**
   * Slice Zone field in *Accommodation Single*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AccommodationSingleDocumentDataSlicesSlice> /**
   * Meta Title field in *Accommodation Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: accommodation_single.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Accommodation Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: accommodation_single.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Accommodation Single*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_single.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Accommodation Single document from Prismic
 *
 * - **API ID**: `accommodation_single`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccommodationSingleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AccommodationSingleDocumentData>,
    "accommodation_single",
    Lang
  >;

type BlogDocumentDataSlicesSlice =
  | BlogListSliceSlice
  | SmallHeroSliceSlice
  | HeroSliceSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogDocumentData>, "blog", Lang>;

/**
 * Item in *Blog Single → Gallery*
 */
export interface BlogSingleDocumentDataGalleryItem {
  /**
   * Image field in *Blog Single → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_single.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type BlogSingleDocumentDataSlicesSlice = VideoSliceSlice;

/**
 * Content for Blog Single documents
 */
interface BlogSingleDocumentData {
  /**
   * Heading field in *Blog Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_single.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *Blog Single*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_single.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *Blog Single*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_single.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Gallery field in *Blog Single*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_single.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<BlogSingleDocumentDataGalleryItem>>;

  /**
   * Slice Zone field in *Blog Single*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_single.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogSingleDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_single.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_single.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Single*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_single.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Single document from Prismic
 *
 * - **API ID**: `blog_single`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogSingleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogSingleDocumentData>,
    "blog_single",
    Lang
  >;

/**
 * Content for Cancelation Policy documents
 */
interface CancelationPolicyDocumentData {
  /**
   * Heading field in *Cancelation Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cancelation_policy.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Cancelation Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cancelation_policy.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Cancelation Policy document from Prismic
 *
 * - **API ID**: `cancelation_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CancelationPolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CancelationPolicyDocumentData>,
    "cancelation_policy",
    Lang
  >;

type ContactDocumentDataSlicesSlice =
  | ContactFormSliceSlice
  | SmallHeroSliceSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Item in *Destination → Gallery*
 */
export interface DestinationDocumentDataGalleryItem {
  /**
   * Image field in *Destination → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: destination.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type DestinationDocumentDataSlicesSlice = never;

/**
 * Content for Destination documents
 */
interface DestinationDocumentData {
  /**
   * Heading field in *Destination*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: destination.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *Destination*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: destination.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *Destination*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: destination.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Gallery field in *Destination*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: destination.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<DestinationDocumentDataGalleryItem>>;

  /**
   * Slice Zone field in *Destination*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: destination.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DestinationDocumentDataSlicesSlice> /**
   * Meta Title field in *Destination*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: destination.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Destination*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: destination.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Destination*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: destination.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Destination document from Prismic
 *
 * - **API ID**: `destination`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DestinationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DestinationDocumentData>,
    "destination",
    Lang
  >;

type DestinationsDocumentDataSlicesSlice =
  | DestinationListSliceSlice
  | SmallHeroSliceSlice;

/**
 * Content for Destinations documents
 */
interface DestinationsDocumentData {
  /**
   * Slice Zone field in *Destinations*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: destinations.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DestinationsDocumentDataSlicesSlice> /**
   * Meta Title field in *Destinations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: destinations.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Destinations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: destinations.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Destinations*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: destinations.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Destinations document from Prismic
 *
 * - **API ID**: `destinations`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DestinationsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DestinationsDocumentData>,
    "destinations",
    Lang
  >;

type ForSaleDocumentDataSlicesSlice =
  | SmallHeroSliceSlice
  | HeroSliceSlice
  | ForSaleListSliceSlice;

/**
 * Content for For Sale documents
 */
interface ForSaleDocumentData {
  /**
   * Slice Zone field in *For Sale*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ForSaleDocumentDataSlicesSlice> /**
   * Meta Title field in *For Sale*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: for_sale.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *For Sale*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: for_sale.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *For Sale*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * For Sale document from Prismic
 *
 * - **API ID**: `for_sale`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ForSaleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ForSaleDocumentData>,
    "for_sale",
    Lang
  >;

/**
 * Item in *For Sale Single → Gallery*
 */
export interface ForSaleSingleDocumentDataGalleryItem {
  /**
   * Image field in *For Sale Single → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type ForSaleSingleDocumentDataSlicesSlice = never;

/**
 * Content for For Sale Single documents
 */
interface ForSaleSingleDocumentData {
  /**
   * Heading field in *For Sale Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Gallery field in *For Sale Single*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<ForSaleSingleDocumentDataGalleryItem>>;

  /**
   * Guests Prikaz field in *For Sale Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.guestsPrikaz
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  guestsPrikaz: prismic.KeyTextField;

  /**
   * m2 field in *For Sale Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.sqm
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sqm: prismic.KeyTextField;

  /**
   * Bedrooms field in *For Sale Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.bedrooms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bedrooms: prismic.KeyTextField;

  /**
   * Bathrooms field in *For Sale Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.bathrooms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bathrooms: prismic.KeyTextField;

  /**
   * Content field in *For Sale Single*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Price field in *For Sale Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * Google Map Embed field in *For Sale Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.google_map_embed
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google_map_embed: prismic.KeyTextField;

  /**
   * Slice Zone field in *For Sale Single*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ForSaleSingleDocumentDataSlicesSlice> /**
   * Meta Title field in *For Sale Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: for_sale_single.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *For Sale Single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: for_sale_single.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *For Sale Single*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_single.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * For Sale Single document from Prismic
 *
 * - **API ID**: `for_sale_single`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ForSaleSingleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ForSaleSingleDocumentData>,
    "for_sale_single",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | NewsletterSliceSlice
  | VideoSliceSlice
  | AccommodationListSliceSlice
  | HeroSliceSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Payment Details documents
 */
interface PaymentDetailsDocumentData {
  /**
   * Heading field in *Payment Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_details.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Payment Details*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_details.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Payment Details document from Prismic
 *
 * - **API ID**: `payment_details`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PaymentDetailsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PaymentDetailsDocumentData>,
    "payment_details",
    Lang
  >;

type PrivacyPolicyDocumentDataSlicesSlice = never;

/**
 * Content for Privacy Policy documents
 */
interface PrivacyPolicyDocumentData {
  /**
   * Heading field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *Privacy Policy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *Privacy Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Privacy Policy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PrivacyPolicyDocumentDataSlicesSlice> /**
   * Meta Title field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: privacy_policy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: privacy_policy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Privacy Policy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Privacy Policy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyPolicyDocumentData>,
    "privacy_policy",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Company Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: AdriaVacay, vl. Josip Čorić
   * - **API ID Path**: settings.company_name
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Address Line 1 field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Street and name
   * - **API ID Path**: settings.address_line_1
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_line_1: prismic.KeyTextField;

  /**
   * Address Line 2 field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: City, ZIP, Country
   * - **API ID Path**: settings.address_line_2
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_line_2: prismic.KeyTextField;

  /**
   * Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: info@example.com
   * - **API ID Path**: settings.email
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +385 97 666 35 32
   * - **API ID Path**: settings.phone
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Phone 2 field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +385 99 111 22 33
   * - **API ID Path**: settings.phone2
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone2: prismic.KeyTextField;

  /**
   * VAT / OIB field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: HR12345678901
   * - **API ID Path**: settings.vat
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vat: prismic.KeyTextField /**
   * Facebook URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.facebook_url
   * - **Tab**: Social Media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  facebook_url: prismic.LinkField;

  /**
   * Instagram URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.instagram_url
   * - **Tab**: Social Media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_url: prismic.LinkField /**
   * Site Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: AdriaVacay
   * - **API ID Path**: settings.site_name
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  site_name: prismic.KeyTextField;

  /**
   * Default OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type TermsAndConditionsDocumentDataSlicesSlice = never;

/**
 * Content for Terms and Conditions documents
 */
interface TermsAndConditionsDocumentData {
  /**
   * Heading field in *Terms and Conditions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_and_conditions.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *Terms and Conditions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_and_conditions.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *Terms and Conditions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_and_conditions.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Terms and Conditions*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_and_conditions.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TermsAndConditionsDocumentDataSlicesSlice> /**
   * Meta Title field in *Terms and Conditions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: terms_and_conditions.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Terms and Conditions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: terms_and_conditions.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Terms and Conditions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_and_conditions.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Terms and Conditions document from Prismic
 *
 * - **API ID**: `terms_and_conditions`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TermsAndConditionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TermsAndConditionsDocumentData>,
    "terms_and_conditions",
    Lang
  >;

export type AllDocumentTypes =
  | AboutUsDocument
  | AccommodationDocument
  | AccommodationSingleDocument
  | BlogDocument
  | BlogSingleDocument
  | CancelationPolicyDocument
  | ContactDocument
  | DestinationDocument
  | DestinationsDocument
  | ForSaleDocument
  | ForSaleSingleDocument
  | HomepageDocument
  | PaymentDetailsDocument
  | PrivacyPolicyDocument
  | SettingsDocument
  | TermsAndConditionsDocument;

/**
 * Primary content in *AccommodationListSlice → Default → Primary*
 */
export interface AccommodationListSliceSliceDefaultPrimary {
  /**
   * Heading field in *AccommodationListSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_list_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *AccommodationListSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_list_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Limit field in *AccommodationListSlice → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation_list_slice.default.primary.limit
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  limit: prismic.SelectField<
    "No limit" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8"
  >;
}

/**
 * Default variation for AccommodationListSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccommodationListSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccommodationListSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AccommodationListSlice*
 */
type AccommodationListSliceSliceVariation = AccommodationListSliceSliceDefault;

/**
 * AccommodationListSlice Shared Slice
 *
 * - **API ID**: `accommodation_list_slice`
 * - **Description**: AccommodationListSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccommodationListSliceSlice = prismic.SharedSlice<
  "accommodation_list_slice",
  AccommodationListSliceSliceVariation
>;

/**
 * Default variation for BlogListSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogListSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BlogListSlice*
 */
type BlogListSliceSliceVariation = BlogListSliceSliceDefault;

/**
 * BlogListSlice Shared Slice
 *
 * - **API ID**: `blog_list_slice`
 * - **Description**: BlogListSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogListSliceSlice = prismic.SharedSlice<
  "blog_list_slice",
  BlogListSliceSliceVariation
>;

/**
 * Primary content in *ContactFormSlice → Default → Primary*
 */
export interface ContactFormSliceSliceDefaultPrimary {
  /**
   * Heading field in *ContactFormSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Company details field in *ContactFormSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.default.primary.company_details
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_details: prismic.RichTextField;

  /**
   * Phone field in *ContactFormSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Phone 2 field in *ContactFormSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.default.primary.phone2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone2: prismic.KeyTextField;

  /**
   * Email field in *ContactFormSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Address field in *ContactFormSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.default.primary.address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;
}

/**
 * Default variation for ContactFormSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactFormSlice*
 */
type ContactFormSliceSliceVariation = ContactFormSliceSliceDefault;

/**
 * ContactFormSlice Shared Slice
 *
 * - **API ID**: `contact_form_slice`
 * - **Description**: ContactFormSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceSlice = prismic.SharedSlice<
  "contact_form_slice",
  ContactFormSliceSliceVariation
>;

/**
 * Default variation for DestinationListSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DestinationListSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *DestinationListSlice*
 */
type DestinationListSliceSliceVariation = DestinationListSliceSliceDefault;

/**
 * DestinationListSlice Shared Slice
 *
 * - **API ID**: `destination_list_slice`
 * - **Description**: DestinationListSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DestinationListSliceSlice = prismic.SharedSlice<
  "destination_list_slice",
  DestinationListSliceSliceVariation
>;

/**
 * Primary content in *ForSaleListSlice → Default → Primary*
 */
export interface ForSaleListSliceSliceDefaultPrimary {
  /**
   * Heading field in *ForSaleListSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_list_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *ForSaleListSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: for_sale_list_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for ForSaleListSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ForSaleListSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ForSaleListSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ForSaleListSlice*
 */
type ForSaleListSliceSliceVariation = ForSaleListSliceSliceDefault;

/**
 * ForSaleListSlice Shared Slice
 *
 * - **API ID**: `for_sale_list_slice`
 * - **Description**: ForSaleListSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ForSaleListSliceSlice = prismic.SharedSlice<
  "for_sale_list_slice",
  ForSaleListSliceSliceVariation
>;

/**
 * Primary content in *HeroSlice → Default → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Image field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Subtitle field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Button Text field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Heading start field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.heading_start
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading_start: prismic.KeyTextField;

  /**
   * Heading animated 1 field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.heading_animated_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading_animated_1: prismic.KeyTextField;

  /**
   * Heading animated 2 field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.heading_animated_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading_animated_2: prismic.KeyTextField;

  /**
   * Heading animated 3 field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.heading_animated_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading_animated_3: prismic.KeyTextField;

  /**
   * Heading end field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.heading_end
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading_end: prismic.KeyTextField;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

/**
 * Primary content in *NewsletterSlice → Default → Primary*
 */
export interface NewsletterSliceSliceDefaultPrimary {
  /**
   * Heading field in *NewsletterSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subscribe to our newsletter
   * - **API ID Path**: newsletter_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *NewsletterSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get the latest villa deals and travel tips.
   * - **API ID Path**: newsletter_slice.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Mailchimp API Key field in *NewsletterSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-usX
   * - **API ID Path**: newsletter_slice.default.primary.mailchimp_api_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mailchimp_api_key: prismic.KeyTextField;

  /**
   * Mailchimp Audience ID field in *NewsletterSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: abc123def456
   * - **API ID Path**: newsletter_slice.default.primary.mailchimp_audience_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mailchimp_audience_id: prismic.KeyTextField;

  /**
   * Mailchimp Server Prefix field in *NewsletterSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: us1
   * - **API ID Path**: newsletter_slice.default.primary.mailchimp_server
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mailchimp_server: prismic.KeyTextField;
}

/**
 * Default variation for NewsletterSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsletterSlice*
 */
type NewsletterSliceSliceVariation = NewsletterSliceSliceDefault;

/**
 * NewsletterSlice Shared Slice
 *
 * - **API ID**: `newsletter_slice`
 * - **Description**: Email newsletter signup connected to Mailchimp
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSliceSlice = prismic.SharedSlice<
  "newsletter_slice",
  NewsletterSliceSliceVariation
>;

/**
 * Item in *SelectedDestinations → Default → Primary → Selected Destinations*
 */
export interface SelectedDestinationsSliceDefaultPrimarySelectedDestinationsItem {
  /**
   * Destination or Blog field in *SelectedDestinations → Default → Primary → Selected Destinations*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: selected_destinations.default.primary.selected_destinations[].destination
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  destination: prismic.ContentRelationshipField<"destination" | "blog_single">;
}

/**
 * Primary content in *SelectedDestinations → Default → Primary*
 */
export interface SelectedDestinationsSliceDefaultPrimary {
  /**
   * Heading field in *SelectedDestinations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: selected_destinations.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Selected Destinations field in *SelectedDestinations → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: selected_destinations.default.primary.selected_destinations[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  selected_destinations: prismic.GroupField<
    Simplify<SelectedDestinationsSliceDefaultPrimarySelectedDestinationsItem>
  >;
}

/**
 * Default variation for SelectedDestinations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SelectedDestinationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SelectedDestinationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SelectedDestinations*
 */
type SelectedDestinationsSliceVariation = SelectedDestinationsSliceDefault;

/**
 * SelectedDestinations Shared Slice
 *
 * - **API ID**: `selected_destinations`
 * - **Description**: SelectedDestinations
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SelectedDestinationsSlice = prismic.SharedSlice<
  "selected_destinations",
  SelectedDestinationsSliceVariation
>;

/**
 * Primary content in *SmallHeroSlice → Default → Primary*
 */
export interface SmallHeroSliceSliceDefaultPrimary {
  /**
   * Heading field in *SmallHeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: small_hero_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *SmallHeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_hero_slice.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SmallHeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallHeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SmallHeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SmallHeroSlice*
 */
type SmallHeroSliceSliceVariation = SmallHeroSliceSliceDefault;

/**
 * SmallHeroSlice Shared Slice
 *
 * - **API ID**: `small_hero_slice`
 * - **Description**: SmallHeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallHeroSliceSlice = prismic.SharedSlice<
  "small_hero_slice",
  SmallHeroSliceSliceVariation
>;

/**
 * Primary content in *VideoSlice → Default → Primary*
 */
export interface VideoSliceSliceDefaultPrimary {
  /**
   * YouTube URL field in *VideoSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter YouTube video URL
   * - **API ID Path**: video_slice.default.primary.youtube_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtube_url: prismic.KeyTextField;
}

/**
 * Default variation for VideoSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: VideoSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoSlice*
 */
type VideoSliceSliceVariation = VideoSliceSliceDefault;

/**
 * VideoSlice Shared Slice
 *
 * - **API ID**: `video_slice`
 * - **Description**: VideoSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceSlice = prismic.SharedSlice<
  "video_slice",
  VideoSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataGalleryItem,
      AboutUsDocumentDataSlicesSlice,
      AccommodationDocument,
      AccommodationDocumentData,
      AccommodationDocumentDataSlicesSlice,
      AccommodationSingleDocument,
      AccommodationSingleDocumentData,
      AccommodationSingleDocumentDataGalleryItem,
      AccommodationSingleDocumentDataPricingItem,
      AccommodationSingleDocumentDataDiscountsItem,
      AccommodationSingleDocumentDataDistancesItem,
      AccommodationSingleDocumentDataReviewsItem,
      AccommodationSingleDocumentDataFeaturesItem,
      AccommodationSingleDocumentDataSlicesSlice,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogSingleDocument,
      BlogSingleDocumentData,
      BlogSingleDocumentDataGalleryItem,
      BlogSingleDocumentDataSlicesSlice,
      CancelationPolicyDocument,
      CancelationPolicyDocumentData,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      DestinationDocument,
      DestinationDocumentData,
      DestinationDocumentDataGalleryItem,
      DestinationDocumentDataSlicesSlice,
      DestinationsDocument,
      DestinationsDocumentData,
      DestinationsDocumentDataSlicesSlice,
      ForSaleDocument,
      ForSaleDocumentData,
      ForSaleDocumentDataSlicesSlice,
      ForSaleSingleDocument,
      ForSaleSingleDocumentData,
      ForSaleSingleDocumentDataGalleryItem,
      ForSaleSingleDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PaymentDetailsDocument,
      PaymentDetailsDocumentData,
      PrivacyPolicyDocument,
      PrivacyPolicyDocumentData,
      PrivacyPolicyDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      TermsAndConditionsDocument,
      TermsAndConditionsDocumentData,
      TermsAndConditionsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccommodationListSliceSlice,
      AccommodationListSliceSliceDefaultPrimary,
      AccommodationListSliceSliceVariation,
      AccommodationListSliceSliceDefault,
      BlogListSliceSlice,
      BlogListSliceSliceVariation,
      BlogListSliceSliceDefault,
      ContactFormSliceSlice,
      ContactFormSliceSliceDefaultPrimary,
      ContactFormSliceSliceVariation,
      ContactFormSliceSliceDefault,
      DestinationListSliceSlice,
      DestinationListSliceSliceVariation,
      DestinationListSliceSliceDefault,
      ForSaleListSliceSlice,
      ForSaleListSliceSliceDefaultPrimary,
      ForSaleListSliceSliceVariation,
      ForSaleListSliceSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      NewsletterSliceSlice,
      NewsletterSliceSliceDefaultPrimary,
      NewsletterSliceSliceVariation,
      NewsletterSliceSliceDefault,
      SelectedDestinationsSlice,
      SelectedDestinationsSliceDefaultPrimarySelectedDestinationsItem,
      SelectedDestinationsSliceDefaultPrimary,
      SelectedDestinationsSliceVariation,
      SelectedDestinationsSliceDefault,
      SmallHeroSliceSlice,
      SmallHeroSliceSliceDefaultPrimary,
      SmallHeroSliceSliceVariation,
      SmallHeroSliceSliceDefault,
      VideoSliceSlice,
      VideoSliceSliceDefaultPrimary,
      VideoSliceSliceVariation,
      VideoSliceSliceDefault,
    };
  }
}
