// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accommodation_list_slice: dynamic(() => import("./AccommodationListSlice")),
  apartment_list_slice: dynamic(() => import("./ApartmentListSlice")),
  blog_list_slice: dynamic(() => import("./BlogListSlice")),
  contact_form_slice: dynamic(() => import("./ContactFormSlice")),
  destination_list_slice: dynamic(() => import("./DestinationListSlice")),
  for_sale_list_slice: dynamic(() => import("./ForSaleListSlice")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  holiday_homes_list_slice: dynamic(() => import("./HolidayHomesListSlice")),
  newsletter_slice: dynamic(() => import("./NewsletterSlice")),
  selected_destinations: dynamic(() => import("./SelectedDestinations")),
  small_hero_slice: dynamic(() => import("./SmallHeroSlice")),
  team_slice: dynamic(() => import("./TeamSlice")),
  video_slice: dynamic(() => import("./VideoSlice")),
};
